### ISSUE TITLE
Class scoverage.Location incompatible with SBT 1.4.3+

### ISSUE THREAD

**Issue by eltherion** [scoverage/sbt-scoverage#318]
Hi! I updated SBT the latest to 1.4.3 and when opening sbt session for the code:
```scala
val location = Location(pkg.text,
        classname.text,
        fullClassName.text,
        ClassType fromString classType.text,
        method.text,
        source.text)
```
I get error:
```bash
Symbol 'term scala.tools.nsc' is missing from the classpath.
[error] This symbol is required by 'value scoverage.Location.global'.
[error] Make sure that term nsc is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Location.class' was compiled against an incompatible version of scala.tools.
[error]       val location = Location(pkg.text,
[error]                      ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```
How can it be fixed?

**Comment by eltherion** [comment]
**Update:** Works with sbt 1.4.4. Probably it'll be working with higher versions, too.
