### PR TITLE
Update Default Scoverage Version

### LINKED ISSUE #295: Build failure with Scala 2.13.1
https://travis-ci.org/plokhotnyuk/expression-evaluator/jobs/586472890

```
error] ## Exception when compiling 1 sources to /Users/travis/build/plokhotnyuk/expression-evaluator/target/scala-2.13/classes
[error] java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
[error] scoverage.ScoverageInstrumentationComponent$$anon$1.run(plugin.scala:119)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
...
```

https://travis-ci.org/plokhotnyuk/jsoniter-scala/jobs/586468216

```
[error] ## Exception when compiling 4 sources to /Users/travis/build/plokhotnyuk/jsoniter-scala/jsoniter-scala-core/target/scala-2.13/classes
[error] java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
[error] scoverage.ScoverageInstrumentationComponent$$anon$1.run(plugin.scala:119)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
```

### PR DESCRIPTION
**Pull request by D-Roch**
Add support for Scala 2.13.1

This fixes #295 by defaulting to a version of scalac-scoverage-plugin that is compatible with every scala version known to man except for 2.13.0.

### CODE REVIEW

**Comment by redkhalil** [comment]
Would this work with Scala 2.12.13?
