### ISSUE TITLE
NoSuchMethodError for scala 2.12.13

### ISSUE THREAD

**Issue by aaabramov** [scoverage/sbt-scoverage#319]
Error: `java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter`

Reference and all details: https://github.com/sbt/sbt/issues/6251

Error: https://github.com/bitcoin-s/bitcoin-s/pull/2509/checks (credits to https://github.com/sbt/sbt/issues/6251#issuecomment-759674809 / @Christewart)

**Comment by eed3si9n** [comment]
Unlike scala-library, there's no binary compatibility guarantees between two patch releases of scala-compiler. Thus well-designed compiler plugins are released with

```scala
    crossVersion := CrossVersion.full,
    crossTarget := target.value / s"scala-${scalaVersion.value}",
```

However, sbt-scoverage seems to be using `%%`, which is suspicious:

https://github.com/scoverage/sbt-scoverage/blob/ddec737ab77770f51abc1af4a0fb421ed1ba8ca8/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L55-L65

In the case of Scala 2.12.13, binary compatibility was intentionally broken in https://github.com/scala/scala/pull/9300.

**Comment by solarmosaic-kflorence** [comment]
Any idea when this will be fixed? Considering disabling `scoverage` as we need to upgrade to 2.12.13 for other reasons.

**Comment by blast-hardcheese** [comment]
I'm giving a PR a shot. Starting from Eugine's comment from earlier, I presume `%%%` is the way to go, but I've not worked with the `portable-scala` infrastructure before, so we'll see how far I get.

**Comment by SethTisue** [comment]
@D-Roch @gslowikowski are you guys around to merge a PR, if one was submitted...?

**Comment by D-Roch** [comment]
@SethTisue I can do it

**Comment by jimm-porch** [comment]
Bonus request - It would be sweet if the [scoverage homepage](https://github.com/scoverage/sbt-scoverage) had a table listing all supported versions.  Scala devs are so used to major-version compatibility that it is very surprising when a library only supports specific minor versions, and it would save some time if they were explicitly called out in the README.

**Comment by blast-hardcheese** [comment]
Status update: I failed at my initial attempts -- I'll give another shot at it next week. The particular way the runtime is depended on seems less inclined to be compatible with `%%%` all my attempts to get it working with local publishing have failed so far.

**Comment by eed3si9n** [comment]
Sorry I meant that instead of `%%`,`.cross(CrossVersion.full)` should be used like `("org.typelevel" % "kind-projector" % "0.11.3").cross(CrossVersion.full)`.

**Comment by blast-hardcheese** [comment]
@eed3si9n Totally missed that -- I thought it was similar to how scalajs worked. Thanks!

**Comment by blast-hardcheese** [comment]
That was the trick. Gonna clean up a source compatibility issue between different versions of scalac then open the PRs

**Comment by blast-hardcheese** [comment]
OK. That should do it.

**Comment by blast-hardcheese** [comment]
This is still an issue, it got automatically closed.

- https://github.com/scoverage/scalac-scoverage-plugin/pull/306 needs to be merged and released
- https://github.com/scoverage/sbt-scoverage/blob/master/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L14 needs to be bumped to the new version
- then sbt-scoverage needs to be released

**Comment by blast-hardcheese** [comment]
@D-Roch Is there something else required in order to release `scalac-scoverage-plugin`? I can open the follow-up PR to bump the version in sbt-scoverage so we can resolve this

**Comment by bal-dx** [comment]
@blast-hardcheese @D-Roch Thank you so much for looking into this :) I was wondering if there were any updates on this?

**Comment by blast-hardcheese** [comment]
@bal-dx [It doesn't appear that the new version of `scalac-scoverage-plugin` has been released yet](https://search.maven.org/search?q=g:org.scoverage%20a:scalac-scoverage-plugin_2.12*) (all releases are still for the minor version, not `CrossVersion.full`), so we are unable to proceed with the patch to sbt-scoverage.

**Comment by zantekk-dev** [comment]
@D-Roch @blast-hardcheese Do we have a rough ETA on when this will be completed / released?

**Comment by blast-hardcheese** [comment]
@D-Roch indicates he's busy, @gslowikowski may be around to release `scalac-scoverage-plugin`, which is what's blocking us now.

If there's a need to widen the maintainer group if the current maintainers aren't available to keep things moving, this could also be a discussion worth having. Additionally, if a company is willing or interested in funding this project, presumably that would be welcome (again, depending on the desires of the current maintainers).

**Comment by james-work-account** [comment]
FWIW I've been looking into upgrading Scala `2.12.12` -> `2.12.13` on one of my projects and was getting `java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;` errors with scoverage `1.6.1`.

Downgrading scoverage to `1.5.1` allowed me to upgrade to Scala `2.12.13` with no issues, whereas keeping scoverage at `1.6.1` threw errors. No idea why, just thought I'd share.

**Comment by mcanlas** [comment]
Are there any updates on how this issue will be fixed? Are the current maintainers available to release an update or widen the group?

**Comment by niyassait** [comment]
The issue is closed and the release hasn't been made yet. Is there any other ticket to track progress on the release?

**Comment by fehu** [comment]
@niyassait 
https://github.com/scoverage/sbt-scoverage/issues/321
